[package]
name = "ars-proxy"
version = "0.1.1"
authors = ["Michele Federici (@ps1dr3x) <michele@federici.tech>"]

[dependencies]
futures = "0.1.23"
native-tls = "0.2"
tokio = "0.1.7"
tokio-tls = "0.2"
hyper = "0.12"
hyper-tls = "0.3.0"
